language: php

php:
 - 5.6

before_script:
 - composer install
 - php -S localhost:8000 index.php &
 - wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar
 - java -jar selenium-server-standalone-2.46.0.jar > /dev/null &
 - sleep 5

script:
 - php test.php